apiVersion: v1
kind: Service
metadata:  
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: api
status:
  loadBalancer: {}
