apiVersion: v1
kind: Service
metadata:  
  labels:
    app: location
  name: location
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
  type: LoadBalancer
  selector:
    app: location
status:
  loadBalancer: {}
